### PR TITLE
New vulners scanner

### PR DESCRIPTION
**Pull request by gmiu**
@cedwards / @basepi, I finally have the new Vulners.com scanner.

New files:

- hubblestack_nova/vulners_scanner.py
- hubblestack_nova_profiles/vulners_scanner.yaml

Things left to do: add logging.

Also, please look at how the Vulners.com response JSON from [here](https://blog.vulners.com/linux-vulnerability-audit-in-vulners/) looks and let me know if you think of any relevant other data to return.

### CODE REVIEW

**Comment by basepi** [comment]
One question I have along the same lines as the cve_scan_v2 -- do we want to return successes? Not returning successes results in some weirdness if there are no vulnerabilities and we're not running any other audits, but returning successes throws off the compliance percentage, since every installed package is a "success" if not vulnerable. Thoughts?

**Comment by gmiu** [comment]
I don't think printing the whole list of safe packages has any point. Maybe just having it in Splunk might be useful. For now, I made the module to return a small report: `Success: x out of y`.

**Comment by basepi** [comment]
Ah, I missed that, thanks. Looking forward to seeing the logging and error handling, then we'll probably get this reviewed and merged.

**Comment by basepi** [comment]
@avb76 Any updates on adding some logging/error handling?

**Comment by gmiu** [comment]
@basepi, sorry for the ultra long delay. I think I've covered the logging/error handling.

**Comment by vulnersCom** [comment]
Wow!)) Great news =) Thank you, fellows)

**Pull request merged**
