### PR TITLE
Adds ability to pass parameters through to Nova modules

### PR DESCRIPTION
**Pull request by absolutejam**
I was pulling my hair out while trying to debug why my command module wasn't doing what I wanted it to do, and thought there really ought to be a way to see what the actual value returned from the `cmd.run` was.

Let me know what you think :smile:

### CODE REVIEW

**Comment by basepi** [comment]
This has the potential to make returns much larger, if you're parsing small pieces of output out of large output blocks. Maybe it should be hidden behind a configuration flag?

**Comment by absolutejam** [comment]
Yeah I was a bit worried about that. Would adding a flag for this pollute `hubble.py`, or could we add something along the lines of `--extra-vars` that also respect pillars?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by basepi** [comment]
You could add it as an argument that passes through or as a `hubblestack:` config value. I don't mind either way.

**Comment by absolutejam** [comment]
Spent a little time figuring what I think the best way to do this is, and I think replacing the `verbose` option with a dict called `module_params` would be the most universal option. Then this could be specified at run with `module_params='parameter=value'` or `module_params='{ "parameter": "value" }'`.

From here, any modules that have specific configuration parameters expect a key in `module_params`, ideally prefixed with the module name as not to cause clashes.

Obviously this poses a breaking change to all nova modules, but this could help extensibility in the long run.

**Comment by basepi** [comment]
This could potentially work. However, I think it might be more pythonic if we just use `**kwargs`. Have hubble.py take `**kwargs`, and then unroll those kwargs into the module calls. Modules can take their specific keyword arguments, as well as `**kwargs` to catch any that aren't specific to that module.

Still a change to all the modules but a much cleaner one, I think, since you can just pass in module-specific arguments just like any other arguments at call time.

**Comment by absolutejam** [comment]
Funny you should mention because I spent a little while in my lunch break tinkering with this before I remembered about `kwargs` and felt like kicking myself for overlooking it! I have a semi-working solution that passes through kwargs to the Nova module, but it uses `config.get` on a `module_params` key then looks for json passed in as `module_params` at the CLI (emulating how the `pillar` parameter works in Salt). I feel like just using kwargs in `hubble.py` would make it more unfriendly for new users as there could suddenly be a lot of random parameters flying about, whereas this maintains a single parent parameter.

I'll try and commit my work so far and see what you think.

**Comment by absolutejam** [comment]
Renamed issue to focus on the broader subject of passing parameters to Nova modules & pushed some changes :smile: 

Added `command.py` as an example and I can do the rest if this looks okay.

(Couldn't figure out how to rename the branch :man_shrugging:)

**Comment by absolutejam** [comment]
Only outstanding issue is that there's no validation on the `config.get` to ensure that the dict will translate to kwargs effectively.

**Comment by basepi** [comment]
I'm still not quite convinced on the module_params thing. Writing JSON on the command line is annoying, especially compared to just throughing a couple of `<arg>=<value>` additions onto the end of your command.

Why not just have it take `**kwargs` at hubble.py and document `**kwargs` the same way you've documented module_params? "Any additional keyword arguments passed into hubble.py will be passed to the modules to be used or ignored depending on the module."

I understand that it might not be quite as self-documenting, but it's way cleaner to use.

**Comment by basepi** [comment]
Beautiful, thanks!

**Pull request merged**
