### PR TITLE
Resolved os_version mismatch.

### LINKED ISSUE #181: Os_version mismatch with the one reported from vulners.com
Vulners.com reports 'OSVersion' as found in 'osrelease' grain rather than as in 'osmajorrelease'.

This is an expert of my Ubuntu 14.04 minion grains,

>     os:
>         Ubuntu
>     os_family:
>         Debian
>     osarch:
>         amd64
>     oscodename:
>         trusty
>     osfinger:
>         Ubuntu-14.04
>     osfullname:
>         Ubuntu
>     osmajorrelease:
>         14
>     osrelease:
>         14.04
>     osrelease_info:
>         - 14
>         - 4

Now, download the CVEs for this machine from,
http://vulners.com/api/v3/archive/distributive/?os=ubuntu&version=14.04
You'll notice how OSVersion is reported,

>       "affectedPackage": [
>         {
>           "OS": "Ubuntu",
>           "OSVersion": "14.04",
>           "packageVersion": "1.0.10-0ubuntu1.1",
>           "arch": "noarch",
>           "packageFilename": "UNKNOWN",
>           "packageName": "lxc",
>           "operator": "lt"
>         }
>       ]

See that it matches with the 'osrelease' grain rather than with the 'osmajorrelease'.
So, using 'osmajorrelease' first and then falling back to 'osrelease' as epxressed here,
https://github.com/hubblestack/hubble-salt/blob/develop/hubblestack_nova/cve_scan_v2.py#L99-L101
might lead to mismatch in this comparison,
https://github.com/hubblestack/hubble-salt/blob/develop/hubblestack_nova/cve_scan_v2.py#L272
leaving out vulnerability audits.

### PR DESCRIPTION
**Pull request by chrispetsos**
Further resolves https://github.com/hubblestack/hubble/issues/181.

As it turns out, the OSVersion reported from vulners.com in some cases it maps to "osrelease" grain and in others to "osmajorrelease" grain. So compare with both...
Also reverted how os_version is getting value to, first osmajorrelease, then osrelease as it was before https://github.com/hubblestack/hubble-salt/pull/109, just not to break anything else.
Furthermore, when checking OSVersion from vulners stringify the grains' values because it looks like sometimes they are returned as numbers, resulting to nonexistence with 'in'.

### CODE REVIEW

**Comment by mew1033** [comment]
Did the change to osrelease before osmajorrelease break anything? I thought that was a good change. If it doesn't break anything, I'd rather default to osrelease (more detailed, 14.04) than osmajorrelease (less detailed, 14).

**Comment by basepi** [comment]
More precise as the default is probably a good thing. Maybe just switch your logic to take osmajorrelease first and fall back to osrelease if it's not there?

**Comment by chrispetsos** [comment]
I though it would be good to revert the osrelease/osmajorrelease change, because the os_version variable is used in other places too. The change didn't seem to break anything though.
I'm a bit confused on whether you both suggest the same thing. With this PR, I check osmajorrelease first and then fallback to osrelease. @basepi isn't this what you are proposing? And @mew1033 the contrary? So, which way should I go?

**Comment by basepi** [comment]
Sorry, I just switched them up in my comment. I guess I don't care which way it is.

@mew1033 have we verified what these two grains look like on centos boxes? From just the name, I would expect osrelease to be more specific than osmajorrelease.

**Comment by mew1033** [comment]
Just checked. osrelease is more specific (6.7 or 7.1.xxxx). osmajorrelease is just 6 or 7.

**Comment by chrispetsos** [comment]
OK guys, I'll switch it to osrelease first, then osmajorrelease...

**Comment by basepi** [comment]
Thanks. Sorry for the runaround! :)

**Comment by chrispetsos** [comment]
OK done.

**Pull request merged**
